#!/bin/bash

# turn on the monitor
xrandr --auto

# wait for auto setup
sleep 1

# ... now set to your needs
xrandr --output HDMI1 --off --output DP1 --mode 1920x1200 --pos 0x0 --rotate normal --output eDP1 --off --output VIRTUAL1 --off

echo 'Monitor setup finished'

# disable energy settings
xset -dpms s off

# sound setup
pulseaudio -k

# wait for pulseaudio to start again
sleep 1

# ... now set audio
pacmd set-default-sink alsa_output.pci-0000_00_03.0.hdmi-stereo
pactl set-sink-volume $(audioctl sink) 60%

echo 'Sound setup finished'

# programs
echo 'Starting the main programs now'

# firefox
if ! pidof firefox > /dev/null; then
    i3-msg -q workspace '3: Firefox'
    i3-msg -q exec firefox
fi

# thunderbird
if ! pidof thunderbird > /dev/null; then
    i3-msg -q workspace '4: Thunderbird'
    i3-msg -q exec thunderbird
fi

#spotify
if ! pidof spotify > /dev/null; then
    i3-msg -q exec spotify
fi

# and now go back to main workspace
i3-msg -q workspace '1: Main'

# call wallpaper script again due to resolution problems of my monitor
bg-set

echo 'Done'
