#!/bin/bash

# name of screens
leftMonitor=DVI-I-1-1
rightMonitor=DVI-I-2-2

# turn on the monitors
xrandr --auto

# wait for auto setup
sleep 1 

# ... now set to your needs 
xrandr --output VIRTUAL1 --off --output eDP1 --mode 1920x1080 --pos 3840x0 --rotate normal --output DP1 --off --output HDMI1 --off --output "$leftMonitor" --mode 1920x1080 --pos 0x0 --rotate normal --output "$rightMonitor" --mode 1920x1080 --pos 1920x0 --rotate normal

echo 'Monitor setup finished'

# sound setup
pulseaudio -k

# wait for pulseaudio to start again
sleep 1

# ... now set audio
pacmd set-default-sink alsa_output.usb-DisplayLink_Dell_D3100_USB3.0_Dock_1603160861-02.analog-surround-50
pactl set-sink-volume $(audioctl sink) 60% 

echo 'Sound setup finished'

# programs
echo 'Starting the main programs now'

# firefox
i3-msg -q workspace '3: Firefox'
if ! pidof firefox > /dev/null; then
    i3-msg -q exec firefox
fi
i3-msg -q move workspace to output $rightMonitor

# thunderbird
i3-msg -q workspace '4: Thunderbird'
if ! pidof thunderbird > /dev/null; then
    i3-msg -q exec thunderbird
fi
i3-msg -q move workspace to output eDP1

#spotify
if ! pidof spotify > /dev/null; then
    i3-msg -q exec spotify
fi
i3-msg -q workspace '10: Spotify'
i3-msg -q move workspace to output eDP1

# and now move main workspace to main monitor
i3-msg -q workspace '1: Main'
i3-msg -q move workspace to output $leftMonitor

echo 'Done'
